version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.17.1
    commands:
      - npm install typescript -g
      - npm run install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - package.json
    - server/package.json
    - server/package-lock.json
    - client/package-lock.json
    - client/package.json
    - 'server/dist/**/*'
    - 'client/build/**/*'
