version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install typescript -g
      - npm install
      - npm install --prefix ./client
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run start
artifacts:
  files:
    - package.json
    - package-lock.json
    - client/package-lock.json
    - client/package.json
    - dist/**/*
    - client/build/**/*
  discard-paths: yes
