# This is a basic workflow to help you get started with Actions

name: Deploy to EC2
env:
  DB_HOST: ${{secrets.DB_HOST}}
  DB_NAME: ${{secrets.DB_NAME}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_USERNAME: ${{secrets.DB_USERNAME}}
  FROM_EMAIL: ${{secrets.FROM_EMAIL}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  SECRET: ${{secrets.SECRET}}
  SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Files
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Deploy to Server
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/month-earnings
          remote_host: ${{ secrets.HOST_DNS }}
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Dependencies
        run: npm install
      - name: Install Frontend Dependencies
        run: npm install --prefix frontend
      - name: Build Project
        run: npm run build
